### ISSUE TITLE
Run tests for PHP 'nightly' on Travis

### ISSUE THREAD

**Issue by markbook2** [morpho-os/framework#352]
```
php:
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly
```
